### ISSUE TITLE
TempStringNoAlloc.get attempts to link in the default runtime

### ISSUE THREAD

**Issue by dukc** [skoppe/spasm#25]
When trying to initialize spasm, with this js function
```js
(toDo) => {
        fetch("dmodule.wasm")
        .then(response => response.arrayBuffer())
        .then(buffer => WebAssembly.instantiate(buffer, { env: jsExports }))
        .then(obj =>
        {   spasm.instance = obj.instance;
            obj.instance.exports._start();
            toDo();
        })
        .catch(error => {window.alert("wasm didn't initialize. " + error);})
    },
```
it alerts `wasm didn't initialize. LinkError: import object field '_D4core8internal6string17TempStringNoAlloc3getMFNaNbNiNjNfZAa' is not a Function`.

This happened when I updated LDC to 1.6.0. Didn't pop up with LDC 1.4.0-beta1.

Dub.sdl:
```
name "dmodule"
description "D-borne wasm for grave stone modeler of Ylivieskan Kivihiomo OY"
authors "Ate Eskola"
copyright "(C) Ylivieskan Kivihiomo"
license "proprietary"
dflags "-mtriple=wasm32-unknown-unknown-wasm" "-Oz" "-betterC" "-fvisibility=hidden"
lflags "-strip-all"
dependency "spasm" version="==0.1.13"
targetName "dmodule"
configuration "stoneworks" {
    targetType "executable"
    versions "StoneworksEdition"
}
configuration "salesmen" {
    targetType "executable"
    versions "SalesmenEdition"
}
configuration "internet" {
    targetType "executable"
    versions "InternetEdition"
}
```

Still using Windows 10. D array of DUB invocation arguments is `["dub", "build", "--config=salesmen", "--compiler=ldc2", "--build=debug", "--combined"]`. Adding `"--export-dynamic"` to `lflags` makes no difference.

I checked that spasm has the function in question, at `spasm.rt.array`. So the update made compiler to think it should use the default runtime definition instead, for some reason.

**Comment by skoppe** [comment]
I still need to update spasm with ldc `1.16.0`, that is probably why. I am currently working on memory management (automatic release of js objects and implementing a GC).

Because of the possible breaking changes I will probably do a `0.2.x` release, and then backport compiler updates to `0.13.x`.

**Comment by dukc** [comment]
> I still need to update spasm with ldc `1.16.0`, that is probably why. 

Okay. I finished for today, but next day I'll first try some compiler switches, and if that fails, I'll switch to 1.15.
> 
> I am currently working on memory management (automatic release of js objects and implementing a GC). Because of the possible breaking changes I will probably do a `0.2.x` release, and then backport compiler updates to `0.13.x`.

Wow, cool. Sounds almost like @safe. Good luck!

**Comment by dukc** [comment]
This looks like the most probable cause: https://github.com/ldc-developers/ldc/issues/3098

**Comment by kinke** [comment]
druntime `TempStringNoAlloc` is referenced from the `stdx-allocator` dub package (I checked the wasm libs).

**Comment by dukc** [comment]
> druntime `TempStringNoAlloc` is referenced from the `stdx-allocator` dub package (I checked the wasm libs).

...and `stdx-allocator` can't see the equivalent `spasm` definition. So sounds like it might be that earlier ldc versions do the wrong thing, not 1.16.0. Assuming this is correct, now I can think of a remedy. Thanks.

**Comment by dukc** [comment]
For some reason, I could not find a cause for call of `TempStringNoAlloc` in source code of `stdx-allocator`, or my application.

Anyway, I tested 1.15.0, and it works (but needs adding `--export-dynamic` flag manually to `dub.sdl`), so I'll just use that for now. I'll leave open until works in 1.16.x, or newer.

**Comment by skoppe** [comment]
So, I finally got some time to figure this out. Apparently the _d_array_cast runtime hook is replaced with the __ArrayCast template function as part of an endeavour to replace runtime hooks with templates. Good as that may be, it now means the __ArrayCast function from druntime is compiled into the binary, even in betterC.

__ArrayCast depends on `core.internal.string.unsignedToTempString`, which depends on `TempStringNoAlloc.get`, which is nowhere to be found because we compile in betterC.

@JinShil we really need to restrict these new template hooks to NOT depend on anything but templates.

**Comment by dukc** [comment]
> So, I finally got some time to figure this out. Apparently the _d_array_cast runtime hook is replaced with the __ArrayCast template function as part of an endeavour to replace runtime hooks with templates. Good as that may be, it now means the __ArrayCast function from druntime is compiled into the binary, even in betterC.

Thanks for figuring this out! Sounds interesting.

> @JinShil we really need to restrict these new template hooks to NOT depend on anything but templates.

Yes. Having to include a custom DRuntime (with spasm definitions of those functions) would suck -It already is complicated enough to get D working for specialized enviroments like this. Isn't the very idea of templatizing the runtime done to let one avoid or replace parts of the runtime/standard library without having to fight compiler switches or the linker?

**Comment by skoppe** [comment]
also see https://issues.dlang.org/show_bug.cgi?id=20088

**Comment by skoppe** [comment]
There is a fix in druntime https://github.com/dlang/druntime/pull/2705 it will probably ship in <v2.087.2> or <v2.088.0>.

In the meantime the `0.2.0-beta.1` version of spasm has a custom `object.d` with a `betterC` implementation of the new __ArrayCast.

That version also works with `ldc 1.16.0` and `ldc 1.17.0-beta.1`. See [CHANGELOG.md](https://github.com/skoppe/spasm/blob/master/CHANGELOG.md) and [BUILDING.md](https://github.com/skoppe/spasm/blob/master/BUILDING.md) for more info. There have been a few breaking changes.

It would be great if you can give it a try. I recommend going to `ldc 1.17.0-beta.1` directly, but 16 also works.

**Comment by JinShil** [comment]
> @JinShil we really need to restrict these new template hooks to NOT depend on anything but templates.

Yes, I understand that, but we have to do it incrementally.

**Comment by skoppe** [comment]
I don't understand what you mean by incrementally in this specific case.

**Comment by JinShil** [comment]
I'm referring to the general case, not anything specific.  Converting the existing runtime hooks to templates is a major task. It involves refactoring DMD and druntime simultaneously.  Also, because the existing runtime hooks can be used in `pure`, `@safe`, and `nothrow` code, but are not actually pure, safe, and nothrow, it's very difficult to do without breaking existing code.  Couple that with CTFE issues, `TypeInfo` and BetterC accommodations and you have a very difficult task.  Trying to do it all at once would be too difficult and probably impossible to review, so it needs to be done incrementally.

The approach I've been advocating is...
1.  Create the runtime hook template in druntime, mimicking current behavior
2. Modify DMD to call the new runtime hook template
3. Delete the old non-template runtime hook fom druntime
4. Refactor the body of the new runtime hook template and anything it calls to utilize the new compile-time type information.

Step 4 is still remaining for `__ArrayCast`.  As you said, it needs to be refactored so it only depends on template instantiations and will not require linking to druntime.

**Comment by skoppe** [comment]
That is a very good approach. I remember we briefly discussed it on slack as well.

Except that in this specific case I believe there was also a `1b` step added during review of that PR. If I remember correctly one of the reviewers requested to extend the error logging. All with very good intentions of course. But it does make an already complicated task a little bit more complicated.

I am going to try to build a version of spasm in `betterC` with dmd nightly and run it every night so that I become aware of these issues earlier. https://github.com/skoppe/spasm/projects/2#card-25120622

**Comment by dukc** [comment]
> I am going to try to build a version of spasm in `betterC` with dmd nightly and run it every night so that I become aware of these issues earlier. https://github.com/skoppe/spasm/projects/2#card-25120622

If you want, consider pushing spasm to https://github.com/dlang/ci when you have got it to build, so you don't have to do manual testing. A special library like this would also benefit the core development a lot, catching issues that most DUB libraries cannot.

**Comment by skoppe** [comment]
That is a nice idea. I have already setup a test repo and configured circle ci to run each morning. I am waiting for a new release of `optional` before it will start working.

So I am going to continue with that. If this proves to be valuable I might move it to be part of dlang/ci.
